//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseDetail
    {
        public System.Guid Id { get; set; }
        public System.Guid UserId { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.Guid> CourseId { get; set; }
        public Nullable<int> ProgressStatus { get; set; }
        public Nullable<int> StatusTotal { get; set; }
        public Nullable<System.DateTime> LastAccessed { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateEdited { get; set; }
        public Nullable<bool> IsEnable { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
